### ISSUE TITLE
Twitterのログイン認証をスマホからするとうまくログインできない

### ISSUE THREAD

**Issue by yoshi5170** [yoshi5170/self_acceptance_journey#59]
### Twitter OAuth認証時のブラウザ遷移問題

**問題の概要:**  
TwitterのOAuth認証を利用したログイン機能に問題が発生しています。具体的には、モバイルデバイスのデフォルトのブラウザ（ChoromやSafari) からアクセスし、Twitterログインを試みると、Twitterの公式アプリの組み込みブラウザが開き、そこでの認証が行われます。しかし、認証後にデフォルトのブラウザ（ChoromやSafari) に戻ると、アプリケーションがログイン状態になっていません。また、１回目のログインで必ず毎回失敗してしまいます。２回目ログインをするとログインは成功します。
この問題を解決するための方法などがあれば、ご教示いただけると助かります。

**アプリのURL:**  
また未完成ですが、アプリのURLも以下提示しておきます。

https://accept-me-3b1266a17fff.herokuapp.com/

**再現手順:**  
1. モバイルデバイスのデフォルトブラウザでアプリケーションにアクセス。
2. Twitterログインボタンをクリック。
3. Twitterの公式アプリ内の組み込みブラウザが開く。
4. Twitterでの認証を完了。
5. デフォルトのブラウザに戻ると、ログインが行われていない。

**再現動画：** 

https://github.com/yoshi5170/self_acceptance_journey/assets/122294799/2f97df73-d8be-4920-9727-f4fd040a6aac

**試したこと:**  
この問題を解決できそうな記事を探したのですが見つかりませんでした。
また、RUNTEQ生でTwitterのOAuth認証を導入しているwebアプリもいくつか確認したら皆さん同じ現象が起こっていました。
MacBookなどのPC環境でブラウザから同じアプリケーションにアクセスすると、この問題は発生せず、デフォルトのブラウザで問題なくログインができました。

**考えられる原因:**  
Twitterのアプリ内ブラウザでセットされたセッションやクッキーが外部ブラウザと共有されないため、ユーザーがTwitterのアプリ内ブラウザでログインを完了させた後、外部ブラウザに戻ったときにログイン状態が保持されないのが原因だと考えています。

**Twitterログインに関するコード:**  

<SessionsController >

```
class SessionsController < ApplicationController
  skip_before_action :require_login, only: :create
  def create
    @user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = @user.id
    redirect_to request.env["omniauth.origin"] || root_url, success: t('.success')
  end

  def destroy
    reset_session
    redirect_to root_url, success: t('.success'), status: :see_other
  end

  def failure
    redirect_to root_url, danger: t('.fail')
  end

end
```

<config/initializers/omniauth.rb>

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :twitter2,
           Rails.application.credentials.x[:client_id],
           Rails.application.credentials.x[:client_secret],
           callback_path: ENV['X_CALLBACK_PATH'] || "/auth/twitter2/callback",
           scope: "tweet.read users.read"

  OmniAuth.config.on_failure =
    Proc.new { |env| OmniAuth::FailureEndpoint.new(env).redirect_to_failure }
end
```

**Comment by kenchasonakai** [comment]
Twitter側のバグですかね
下記のページ関係あるか確認してもらえるといいかもです
バグだったらどうしようもないかも

https://twittercommunity.com/t/web-app-oauth-2-0-process-on-mobile-devices/173917/4

**Comment by kenchasonakai** [comment]
こちらもどうぞ
https://x.com/GanoPon/status/1652186707226423296?s=20

**Comment by yoshi5170** [comment]
コメントありがとうございます。

本リリースで導入予定の以下の機能で、Twitterシェアー時に相手のメンションをつけてシェアーできるようにするために、登録ユーザーのTwitterのuser nameをデーターベースに保存したいと考えています。

現在、webアプリのログイン方法はTwitterログインのみとなっていますが、Twitterのアプリ内ブラウザ内でしかログインできない場合、ユーザーにとって使いにくいアプリとなってしまわないかが懸念点です。

以下の2つの選択肢について、どちらが望ましいか、または他の代替案があれば、ご助言をいただければと思います。

1. Twitterログインは使用せずに通常のメール＆パスワード認証やGoogleログインを導入する。これにより、twitterシェアー時に相手のメンションが付けられなくなる。

2. Twitterログインを維持する。ただし、モバイルデバイスではTwitterのアプリ内ブラウザでしかログインできないため、ユーザーエクスペリエンスに影響が出る可能性がある。



#### 本リリースで導入予定の機能
励ましのメッセージをリクエスト＆励ましの言葉を送る

- 自己否定に陥り落ち込んだときに励ましリクエストカードを作成する。
- 作成したリクエストカードをtwitterにシェアーする。
　例えば）”私落ち込んでます”のようなメッセージカードをogp画像を使って表示する。
- Twitter上でその投稿を見つけた人が、そのogp画像をクリックすると励ましの言葉を送るページ飛び励ましのメッセージを作成することができる。
- さらに励ましのメッセージカードを励ましたい相手のメンションをつけてTwitterにシェーアできるようにする。

**Comment by kenchasonakai** [comment]
ご自身ではどちらのが良いと思ってるんでしょうか？

**Comment by yoshi5170** [comment]
コメントありがとうございます。
考えた結果、通常のログイン方法に切り替える方針で進めていこうと思います。
Twitter のメンションをつけてのシェアする問題に関しては、ユーザーにTwitterでのユーザー名を登録するフォームを用意し登録したユーザーにはTwitterのシェアー時にメンションがつけられるようにしたいと思います。

**Comment by kenchasonakai** [comment]
良いと思います！
